### PR TITLE
Fix sound registration

### PR DESCRIPTION
**Pull request by clienthax**
Previously SoundEvent was null when ItemMixTape was initialized.

### CODE REVIEW

**Comment by UKMinecrafted** [comment]
I doubt that we need the gradle wrapper because you can just build it, its also better to get a fresh build of gradle so that nothing is wrong with it.

**Review by Ukaye-dev — CHANGES_REQUESTED** [review]
I doubt that we need the gradle wrapper because you can just build it, its also better to get a fresh build of gradle so that nothing is wrong with it.

**Comment by clienthax** [comment]
If you don't plan to use the gradle wrapper, why bother to include gradlew.bat, which doesn't work without the gradle folder?
It is also good practice to keep it in as forgegradle has incompatibilities with some versions of gradle.

**Comment by Ukaye-dev** [comment]
I just think that josia thought that you could just build your own ver of gradle with the gradle.bat, besides we keep the forge gradle on a specific version, and we haven't run into any problems yet and if we do we'll figure them out, for now, I will pull your sound handler changes but not the gradle

**Pull request merged**
